### ISSUE TITLE
bug: cannot install on RHEL 8.6

### ISSUE THREAD

**Issue by juntao** [second-state/LlamaEdge#73]
### Summary

The script complains that it requires `libopenblas` to install the GGML plugin on RHEL 8.6.

### Reproduction steps

1. Run the `run-llm.sh` script on a CPU-only RHEL 8.6 machine.
2. See the error message.

### Any logs you want to share for showing the specific issue

The command and error

```
# bash <(curl -sSfL 'https://code.flows.network/webhook/iwYN1SdN3AmPgR5ao5Gt/run-llm.sh')
Checking the operating system (macOS and Linux supported) ...
 
Checking prerequisites ...
'libopenblas' is required for wasi-nn plugin to run.
```

The system info

```
# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
 
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"
```

### Model Information

N/A

### Operating system information

RHEL 8.6

### ARCH

amd64

### CPU Information

Intel on HP machines

### Memory Size

N/A

### GPU Information

N/A

### VRAM Size

N/A

**Comment by hydai** [comment]
@juntao 
Could you try to remove the following section and rerun it again?
https://github.com/second-state/LlamaEdge/blob/main/run-llm.sh#L49-L55

We no longer ship any built-in openblas feature in the default assets.

**Comment by hydai** [comment]
This is fixed by https://github.com/second-state/LlamaEdge/pull/77
