### ISSUE TITLE
bug: cannot detect CUDA if the user does not install nvcc

### ISSUE THREAD

**Issue by juntao** [second-state/LlamaEdge#74]
### Summary

The target machine has CUDA 12.2 installed, but it does not have `nvcc`. The installer failed to detect it.

### Reproduction steps

1. Run the `run-llm.sh` script on a RHEL 8.6 machine with CUDA 12.2
2. Failed to install the GGML plugin.

### Any logs you want to share for showing the specific issue

The command and error: (NOTE I believe it tried to find `libopenblas` because it cannot find CUDA.

```
# bash <(curl -sSfL 'https://code.flows.network/webhook/iwYN1SdN3AmPgR5ao5Gt/run-llm.sh')
Checking the operating system (macOS and Linux supported) ...
 
Checking prerequisites ...
'libopenblas' is required for wasi-nn plugin to run.
```

The `nvcc` tool is not found.

```
# nvcc --version
bash: nvcc: command not found...
```

But `nvidia-smi` shows that GPU is installed.

```
# nvidia-smi
Fri Jan 12 11:44:01 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA H100 PCIe               Off | 00000000:47:00.0 Off |                    0 |
| N/A   42C    P0              79W / 350W |  65143MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA H100 PCIe               Off | 00000000:59:00.0 Off |                    0 |
| N/A   44C    P0              83W / 350W |  62544MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA H100 PCIe               Off | 00000000:C2:00.0 Off |                    0 |
| N/A   44C    P0              79W / 350W |  62544MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA H100 PCIe               Off | 00000000:D5:00.0 Off |                    0 |
| N/A   46C    P0              86W / 350W |  62544MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

```

### Model Information

N/A

### Operating system information

RHEL 8.6

### ARCH

amd64

### CPU Information

Intel on HP machines

### Memory Size

N/A

### GPU Information

4x Nvidia H100 with CUDA 12.2

### VRAM Size

4x 64GB

**Comment by hydai** [comment]
@juntao 
Could you please check if `nvcc` is under `/usr/local/cuda/bin/nvcc`? Or does this machine not install CUDA-related tools except for the libraries?

**Comment by hydai** [comment]
Hmmm. Okay, then, I should try to parse the CUDA version from the output of `nvidia-smi`. Reminder: the Jetson Orin doesn't support `nvidia-smi` due to the hardware design, so we cannot directly replace the original `nvcc` way with `nvidia-smi`.

**Comment by juntao** [comment]
So, I guess we need to check both? 😅

**Comment by hydai** [comment]
Yup. We should check both. However, we may need to determine the most elegant way to check CUDA.

**Comment by hydai** [comment]
> As others note, you can also check the contents of the version.txt (.json in recent CUDA versions) using (e.g., on Mac or Linux)

> cat /usr/local/cuda/version.txt

From: https://stackoverflow.com/a/9730706

I am not sure if there is a `VERSION` file for this.

**Comment by juntao** [comment]
For this machine, it does not have `/usr/local/cuda`

**Comment by hydai** [comment]
The installer now supports `nvidia-smi` for version detection.
