### ISSUE TITLE
Feature Request: update the model list in run-llm.sh

### ISSUE THREAD

**Issue by alabulei1** [second-state/LlamaEdge#84]
### Summary

The `run-llm.sh` command is a tool that helps developers get started quickly. I believe we should only support the latest versions of these models. We will provide the full model list on the `model.md` file. https://github.com/second-state/LlamaEdge/blob/main/models.md

**Comment by alabulei1** [comment]
How about the following list?

1. Llama-2-7B-Chat
2. Llama-2-13B-Chat
3. Mistral-7B-Instruct-v0.2
4. Mixtral-8x7B-Instruct-v0.1
5. TinyLlama-1.1B-Chat-v1.0
6. OpenChat-3.5-0106
7. OpenHermes-2.5-Mistral-7B 
8. Starling-LM-7B-alpha
9. Deepseek-Coder-6.7B
10. Deepseek-LLM-7B-Chat
11. SOLAR-10.7B-Instruct-v1.0
12. Orca-2-13B
13. MistralLite-7B
14. Yi-34B
15. Wizard-Vicuna
16. Calm2-7B-Chat
17. ELYZA-japanese-Llama-2-7b-instruct
18. Zephyr-7B-Alpha
19. dolphin-2.6-phi-2
20. Dolphin-2.2-Mistral-7B
21. Neural-Chat-7B-v3-1
22. WizardLM-1.0-Uncensored-CodeLlama-34B
23. WizardLM-7B-V1.0-Uncensored
24. WizardLM-13B-V1.0-Uncensored
25. WizardCoder-Python-7B-V1.0
26. Zephyr-7B-Alpha
27. CausalLM-14B
28. Baichuan2-13B-Chat
29. BELLE-Llama2-13B-Chat

**Comment by apepkuss** [comment]
Closed. #71 focuses on the same issue. Please provide the necessary info about models in #71.
