### ISSUE TITLE
max_token not working?

### ISSUE THREAD

**Issue by jaykchen** [second-state/LlamaEdge#87]
### Summary

in my summarization task, I need to set the max_token parameter so that llm can stop generation at the length I need. Now llm seems continue generating to the n_predict length, which is not my desired result.

**Comment by apepkuss** [comment]
@jaykchen So far, we set `max_tokens` and `stop` via CLI options. Will replace these options with the settings parsed from requests. This change will happen in the `dev` branch first, in case you need to test them. And next release will contain the update. Thanks a lot for the report!

**Comment by apepkuss** [comment]
@hydai Is it possible for the current version of `plugin` to generate a token sequence of a "specified" length? For example, users expect to get an answer containing `n` tokens. The `n` value is set via the `max_tokens` field of a chat request. Here, `max_tokens` is different from `n_predict`.

**Comment by hydai** [comment]
The `n_predict` is already the number of new tokens to predict. If the output is less than `n_predict`, it does nothing; otherwise, it will stop when the `n_predict` is complete.
What does the `max_token` stand for?
Another thing is that when you use `compute_single`, you can control the behavior you want; I have no idea why this will need to be implemented inside the plugin.

Ref: https://github.com/ggerganov/llama.cpp/blob/master/common/common.h#L52C1-L52C78

**Comment by apepkuss** [comment]
According to the [definition](https://platform.openai.com/docs/api-reference/chat/create#chat-create-max_tokens) of `max_tokens` OpenAI defined, it means the maximum number of tokens generated in the "current" round of conversation. The setting only works in the current request, while `n_predict` is more like a "global" setting.

If `n_predict` is 1024,  and `max_tokens` is 512 in the current request, then I can count the number of tokens, and stop calling `compute_single` and return the result once 512 is reached, and without any side-effects for the subsequent requests, right?

**Comment by hydai** [comment]
Yes. And I think this can also be done.

**Comment by jaykchen** [comment]
@apepkuss tested the dev branch and found inconsistent results over runs under different max_tokens settings, and between models
openchat-3.5-0106
![image](https://github.com/second-state/LlamaEdge/assets/39196302/7418e9ba-4791-4f46-a2d1-7acc69d4061d)
![image](https://github.com/second-state/LlamaEdge/assets/39196302/a3d44c4f-036c-4461-a1c7-0cbd3e2d1d9a)
llama2-chat-7B
![image](https://github.com/second-state/LlamaEdge/assets/39196302/855e020e-8cb7-4cde-a1b9-1ee6e223f936)
![image](https://github.com/second-state/LlamaEdge/assets/39196302/7c06af99-9ac4-4cd9-8ab3-d2e50380e709)

**Comment by apepkuss** [comment]
@jaykchen Could you please copy/paste the prompts here? So that I can use your data to do the tests. Thanks a lot!

**Comment by apepkuss** [comment]
As a reference, we did tests in the following environment:

- OS: `macOS 14.2`

- WasmEdge: `v0.13.5`

- wasi-nn_plugin: 
  ```bash
  6b7b18d900626c0acb3d8a5412d18e93e8fadf9837b785f8852f753433c2832c  libwasmedgePluginWasiNN.dylib
  
  8617318da4dd45652a2b15c11c706ced228d9b930cdb643cb5665d67146936c5  ggml-metal.metal
  ```

- llama-api-server.wasm: Compiled with commit `41c88673` on `dev`

- Command and model:
  ```bash
  wasmedge --dir .:. --nn-preload default:GGML:AUTO:openchat-3.5-1210.Q5_K_M.gguf llama-api-server.wasm -p openchat -r '<|end_of_turn|>' --log-prompts -c 1024
  ```

- Prompt string:
  ```text
  Summarize this: Humans are uniquely smart among all the other species on the planet.  We are capable of outstanding feats of technology and engineering.  Then why are we so prone to making mistakes?  And why do we tend to make the same ones time and time again?  When Primate Psychologist Laurie Santos from the Comparative Cognition Lab at Yale University posed this question to her team, they were thinking in particular of the errors of judgement which led to the recent collapse of the financial markets.   Santos came to two possible answers to this question.  Either humans have designed environments which are too complex for us to fully understand, or we are biologically prone to making bad decisions. In order to test these theories, the team selected a group of Brown Capuchin monkeys.  Monkeys were selected for the test because, as distant relatives of humans, they are intelligent and have the capacity to learn.  However, they are not influenced by any of the technological or cultural environments which affect human decision-making.  The team wanted to test whether the capuchin monkeys, when put into similar situations as humans, would make the same mistakes. Of particular interest to the scientists was whether monkeys would make the same mistakes when making financial decisions.  [B] In order to find out, they had to introduce the monkeys to money.  [C] The monkeys soon cottoned on, and as well as learning simple exchange techniques, were soon able to distinguish 'bargains' – If one team-member offered two grapes in exchange for a metal disc and another team-member offered one grape, the monkeys chose the two-grape option.  [D] Interestingly, when the data about the monkey's purchasing strategies was compared with economist's data on human behaviour, there was a perfect match. So, after establishing that the monkey market was operating effectively, the team decided to introduce some problems which humans generally get wrong.  One of these issues is risk-taking.   Imagine that someone gave you $1000.  In addition to this $1000, you can receive either A) an additional $500 or B) someone tosses a coin and if it lands 'heads' you receive an additional $1000, but if it lands 'tails' you receive no more money.  Of these options, most people tend to choose option A.  They prefer guaranteed earnings, rather than running the risk of receiving nothing.  Now imagine a second situation in which you are given $2000.  Now, you can choose to either A) lose $500, leaving you with a total of $1500, or B) toss a coin; if it lands 'heads' you lose nothing, but if it lands 'tails' you lose $1000, leaving you with only $1000.  Interestingly, when we stand to lose money, we tend to choose the more risky choice, option B.  And as we know from the experience of financial investors and gamblers, it is unwise to take risks when we are on a losing streak. So would the monkeys make the same basic error of judgement?  The team put them to the test by giving them similar options.  In the first test, monkeys had the option of exchanging their disc for one grape and receiving one bonus grape, or exchanging the disc for one grape and sometimes receiving two bonus grapes and sometimes receiving no bonus.  It turned out that monkeys, like humans, chose the less risky option in times of plenty.  Then the experiment was reversed.  Monkeys were offered three grapes, but in option A were only actually given two grapes.  In option B, they had a fifty-fifty chance of receiving all three grapes or one grape only.  The results were that monkeys, like humans, take more risks in times of loss. The implications of this experiment are that because monkeys make the same irrational judgements that humans do, maybe human error is not a result of the complexity of our financial institutions, but is imbedded in our evolutionary history.  If this is the case, our errors of judgement will be very difficult to overcome.  On a more optimistic note however, humans are fully capable of overcoming limitations once we have identified them.  By recognising them, we can design technologies which will help us to make better choices in future.
  ```

- Test 1: `max_tokens: 30`
  <img width="1486" alt="image" src="https://github.com/second-state/LlamaEdge/assets/4726889/2c476534-2ccc-4444-b103-820368ced353">

- Test 2: `max_tokens: 128`
  <img width="1506" alt="image" src="https://github.com/second-state/LlamaEdge/assets/4726889/f0c7cafd-83a7-4ac2-90a3-c229350739f5">

**Comment by apepkuss** [comment]
The issue of "one" more token was fixed in the plugin that will be delivered in the next release.
