### ISSUE TITLE
bug:  load library failed:libcudart.so.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by amulettneo** [second-state/LlamaEdge#88]
### Summary

bash: wasmedge: command not found
(base) root@VM-0-9-ubuntu:~# /root/.wasmedge/bin/wasmedge --dir .:. --nn-preload default:GGML:AUTO:openchat-3.5-1210-Q5_K_M.gguf llama-chat.wasm -p openchat -r '<|end_of_turn|>'
[2024-01-17 05:33:58.120] [error] loading failed: invalid path, Code: 0x20
[2024-01-17 05:33:58.120] [error]     load library failed:libcudart.so.12: cannot open shared object file: No such file or directory
[2024-01-17 05:33:58.120] [error] loading failed: invalid path, Code: 0x20
[2024-01-17 05:33:58.120] [error]     load library failed:libcudart.so.12: cannot open shared object file: No such file or directory
unknown option: nn-preload

### Reproduction steps

1,Execute  bash <(curl -sSfL 'https://code.flows.network/webhook/iwYN1SdN3AmPgR5ao5Gt/run-llm.sh')

### Screenshots

![DESCRIPTION](LINK.png)

### Model Information

Openchat

### Operating system information

ubuntu20.04

### ARCH

amd64

### CPU Information

amd

### Memory Size

32G

### GPU Information

T4

### VRAM Size

16G

**Comment by apepkuss** [comment]
@hydai Could you please help with this issue? Thanks a lot!

**Comment by hydai** [comment]
Hi @amulettneo 
The current plugin is built with CUDA 12.2. However, we are going to downgrade to use CUDA 12.0 to build it instead this week. For a workaround, please install the CUDA 12 and the corresponding driver to use it.

I have a question is CUDA 11 still popular? Or most of the NVIDIA users will choose to use CUDA 12? Because our current users based on GTX4080, GTX4090, A10G, and H100 are all using CUDA 12.

**Comment by amulettneo** [comment]
last question done with upgrade to cuda toolkit 12.0
but now question : /root/.wasmedge/bin/wasmedge --dir .:. --nn-preload default:GGML:AUTO:openchat-3.5-1210-Q5_K_M.gguf llama-chat.wasm  -r '<|end_of_turn|>'
[INFO] Model alias: default
[INFO] Prompt context size: 512
[INFO] Number of tokens to predict: 1024
[INFO] Number of layers to run on the GPU: 100
[INFO] Batch size for prompt processing: 512
[INFO] Temperature for sampling: 0.8
[INFO] Penalize repeat sequence of tokens: 1.1
[INFO] Reverse prompt: <|end_of_turn|>
[INFO] Use default system prompt
[INFO] Prompt template: Llama2Chat
[INFO] Log prompts: false
[INFO] Log statistics: false
[INFO] Log all information: false
[2024-01-17 06:18:00.058] [error] [WASI-NN] GGML backend: Error: unable to init model.

**Comment by amulettneo** [comment]
(base) root@VM-0-9-ubuntu:~# /root/.wasmedge/bin/wasmedge --dir .:. --nn-preload default:GGML:AUTO:openchat-3.5-1210-Q5_K_M.gguf llama-chat.wasm -p openchat -r '<|end_of_turn|>'[INFO] Model alias: default
[INFO] Prompt context size: 512
[INFO] Number of tokens to predict: 1024
[INFO] Number of layers to run on the GPU: 100
[INFO] Batch size for prompt processing: 512
[INFO] Temperature for sampling: 0.8
[INFO] Penalize repeat sequence of tokens: 1.1
[INFO] Reverse prompt: <|end_of_turn|>
[INFO] Use default system prompt
[INFO] Prompt template: OpenChat
[INFO] Log prompts: false
[INFO] Log statistics: false
[INFO] Log all information: false
[2024-01-17 06:16:17.020] [error] [WASI-NN] GGML backend: Error: unable to init model.
Error: "Fail to load model into wasi-nn: Backend Error: WASI-NN Backend Error: Caller module passed an invalid argument"

**Comment by apepkuss** [comment]
> --dir .:. --nn-preload default:GGML:AUTO:openchat-3.5-1210-Q5_K_M.gguf llama-chat.wasm -r '<|end_of_turn|>'

The command lacks a required option: `-p`. The correct command is 

```bash
wasmedge --dir .:. --nn-preload default:GGML:AUTO:openchat-3.5-1210-Q5_K_M.gguf llama-chat.wasm -p openchat -r '<|end_of_turn|>'
```

**Comment by hydai** [comment]
Hi @amulettneo 
Could you please verify the checksum and model size of openchat is correct?

**Comment by amulettneo** [comment]
/root/.wasmedge/bin/wasmedge --dir .:. --nn-preload default:GGML:AUTO:openchat-3.5-0106-Q5_K_M.gguf llama-api-server.wasm -p openchat -m OpenChat-3.5-0106 -r '<|end_of_turn|>'

**Comment by amulettneo** [comment]
建议及时更新hf和相关说明文档。

**Comment by apepkuss** [comment]
@amulettneo 在 https://huggingface.co/second-state/openchat-3.5-1210-GGUF/tree/main 下面，有两个Q5_K_M模型文件，其名称不同：`openchat-3.5-1210.Q5_K_M.gguf` 和 `openchat-3.5-1210-Q5_K_M.gguf`。前者是LlamaEdge相关文档中使用的模型。后者是我们新进引入的，用于即将推出的新版本。请根据文档中所使用的模型文件进行下载。新版本推出后，我们将统一使用 `openchat-3.5-1210-Q5_K_M.gguf`。谢谢！
