### ISSUE TITLE
Feature Request: method to run llama-api-server on demand

### ISSUE THREAD

**Issue by jaykchen** [second-state/LlamaEdge#93]
### Summary

WASM is supposed to be a perfect candidate for serverless functions, is there an easy way to run llama-api-server on demand, I mean a script or some tool within the project to make it work. Appreciate your great work!

**Comment by juntao** [comment]
Hmm, you have a VM that can run the llama-api-server. You can certain start / stop the api-server as needed within that VM. I guess I do not understand the requirements ...

**Comment by jaykchen** [comment]
thanks @juntao, I shall approach this in a different way.
